import React, { useState } from 'react';
import { AutoGeneratedRTI, DEMO_AUTO_GENERATED_RTIS } from '../utils/aiRtiGenerator';
import { exportRTIToPDF, exportRTIToText } from '../utils/pdfExport';

interface RTIPageProps {
  userId: string;
}

function RTIPage({ userId }: RTIPageProps) {
  const [rtiDrafts, setRtiDrafts] = useState<AutoGeneratedRTI[]>(DEMO_AUTO_GENERATED_RTIS);
  const [selectedRTI, setSelectedRTI] = useState<AutoGeneratedRTI | null>(null);
  const [filter, setFilter] = useState<'all' | 'ready' | 'downloaded'>('all');

  const filteredDrafts = rtiDrafts.filter(draft => {
    if (filter === 'all') return true;
    return draft.status === filter;
  });

  const handleSelectRTI = (rti: AutoGeneratedRTI) => {
    setSelectedRTI(rti);
  };

  const handleDownloadPDF = (rti: AutoGeneratedRTI) => {
    const filename = `RTI_${rti.defectType}_${rti.location.city.replace(/\s+/g, '_')}_${new Date(rti.generatedAt).toISOString().split('T')[0]}.pdf`;
    
    // Create a mock aggregated report for PDF export
    const mockReport = {
      id: rti.id,
      geohash: '',
      location: { latitude: rti.location.latitude, longitude: rti.location.longitude },
      defectType: rti.defectType,
      averageSeverity: rti.severity,
      reportCount: 1,
      uniqueUsers: [userId],
      firstReported: rti.detection.timestamp,
      lastReported: rti.detection.timestamp,
      credibilityScore: rti.detection.confidence
    };

    exportRTIToPDF(rti.content, mockReport, filename);

    // Mark as downloaded
    setRtiDrafts(prev => prev.map(d => 
      d.id === rti.id ? { ...d, status: 'downloaded' as const } : d
    ));
  };

  const handleDownloadText = (rti: AutoGeneratedRTI) => {
    const filename = `RTI_${rti.defectType}_${rti.location.city.replace(/\s+/g, '_')}_${new Date(rti.generatedAt).toISOString().split('T')[0]}.txt`;
    exportRTIToText(rti.content, filename);

    // Mark as downloaded
    setRtiDrafts(prev => prev.map(d => 
      d.id === rti.id ? { ...d, status: 'downloaded' as const } : d
    ));
  };

  const formatTimeAgo = (timestamp: number): string => {
    const diff = Date.now() - timestamp;
    const hours = Math.floor(diff / 3600000);
    const days = Math.floor(hours / 24);
    
    if (days > 0) return `${days} day${days > 1 ? 's' : ''} ago`;
    if (hours > 0) return `${hours} hour${hours > 1 ? 's' : ''} ago`;
    return 'Just now';
  };

  const getSeverityClass = (severity: number): string => {
    if (severity >= 7) return 'severity-high';
    if (severity >= 4) return 'severity-medium';
    return 'severity-low';
  };

  return (
    <div className="page">
      {/* Header Card */}
      <div className="card">
        <h2 className="card-title">📄 AI-Generated RTI Drafts</h2>
        <p style={{ color: 'var(--text-secondary)', marginBottom: '1rem' }}>
          RTI applications are automatically generated when road defects are detected during your rides. 
          Select a draft, review it, and download to submit physically.
        </p>

        {/* Filter Tabs */}
        <div className="grid grid-3" style={{ gap: '0.5rem' }}>
          <button
            className={`btn ${filter === 'all' ? 'btn-primary' : 'btn-secondary'}`}
            onClick={() => setFilter('all')}
          >
            All ({rtiDrafts.length})
          </button>
          <button
            className={`btn ${filter === 'ready' ? 'btn-primary' : 'btn-secondary'}`}
            onClick={() => setFilter('ready')}
          >
            Ready ({rtiDrafts.filter(d => d.status === 'ready').length})
          </button>
          <button
            className={`btn ${filter === 'downloaded' ? 'btn-primary' : 'btn-secondary'}`}
            onClick={() => setFilter('downloaded')}
          >
            Downloaded ({rtiDrafts.filter(d => d.status === 'downloaded').length})
          </button>
        </div>
      </div>

      {/* RTI Drafts List */}
      <div className="card">
        <h2 className="card-title">Available Drafts</h2>
        
        {filteredDrafts.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-secondary)' }}>
            <p style={{ fontSize: '2rem', marginBottom: '0.5rem' }}>📭</p>
            <p>No RTI drafts available.</p>
            <p style={{ fontSize: '0.875rem' }}>Start a ride to detect road defects and auto-generate RTIs.</p>
          </div>
        ) : (
          <div className="detection-list" style={{ maxHeight: '400px' }}>
            {filteredDrafts.map((rti) => (
              <div
                key={rti.id}
                className="detection-item"
                style={{ 
                  cursor: 'pointer',
                  background: selectedRTI?.id === rti.id ? 'var(--border-light)' : 'transparent',
                  borderLeft: selectedRTI?.id === rti.id ? '3px solid var(--primary)' : '3px solid transparent'
                }}
                onClick={() => handleSelectRTI(rti)}
              >
                <div style={{ flex: 1 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.25rem' }}>
                    <span style={{ fontSize: '1.25rem' }}>
                      {rti.defectType === 'pothole' ? '🕳️' : '⬆️'}
                    </span>
                    <strong className={`detection-type ${rti.defectType}`}>
                      {rti.defectType === 'pothole' ? 'Pothole' : 'Speed Breaker'}
                    </strong>
                    <span className={`status-badge ${rti.status === 'ready' ? 'status-active' : 'status-warning'}`}>
                      {rti.status === 'ready' ? '✓ Ready' : '↓ Downloaded'}
                    </span>
                  </div>
                  <div style={{ fontSize: '0.875rem', color: 'var(--text-secondary)' }}>
                    📍 {rti.location.address}
                  </div>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '0.25rem' }}>
                    🏛️ {rti.location.municipalAuthority} • {formatTimeAgo(rti.generatedAt)}
                  </div>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <div style={{ marginBottom: '0.5rem' }}>
                    <span style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>Severity</span>
                    <div style={{ fontWeight: '700', fontSize: '1.25rem' }}>{rti.severity}/10</div>
                  </div>
                  <div className="severity-bar" style={{ width: '60px' }}>
                    <div 
                      className={`severity-fill ${getSeverityClass(rti.severity)}`}
                      style={{ width: `${rti.severity * 10}%` }}
                    />
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Selected RTI Preview */}
      {selectedRTI && (
        <div className="card">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
            <h2 className="card-title" style={{ marginBottom: 0 }}>RTI Preview</h2>
            <button 
              className="btn btn-secondary"
              onClick={() => setSelectedRTI(null)}
              style={{ padding: '0.5rem 1rem', fontSize: '0.875rem' }}
            >
              ✕ Close
            </button>
          </div>

          {/* Location Info */}
          <div className="alert alert-info" style={{ marginBottom: '1rem' }}>
            <div>
              <strong>📍 {selectedRTI.location.address}</strong>
              <div style={{ fontSize: '0.875rem', marginTop: '0.25rem' }}>
                {selectedRTI.location.city} • Coordinates: {selectedRTI.location.latitude.toFixed(6)}, {selectedRTI.location.longitude.toFixed(6)}
              </div>
              <div style={{ fontSize: '0.875rem' }}>
                🏛️ To: {selectedRTI.location.municipalAuthority}
              </div>
            </div>
          </div>

          {/* RTI Content */}
          <textarea
            className="form-textarea"
            value={selectedRTI.content}
            readOnly
            style={{ 
              minHeight: '350px', 
              fontFamily: "'JetBrains Mono', monospace", 
              fontSize: '0.8rem',
              background: 'var(--border-light)',
              lineHeight: '1.5'
            }}
          />

          {/* Download Buttons */}
          <div className="grid grid-2" style={{ marginTop: '1rem', gap: '1rem' }}>
            <button 
              className="btn btn-primary btn-lg"
              onClick={() => handleDownloadPDF(selectedRTI)}
            >
              📄 Download PDF
            </button>
            <button 
              className="btn btn-secondary btn-lg"
              onClick={() => handleDownloadText(selectedRTI)}
            >
              📋 Download Text
            </button>
          </div>

          {/* Instructions */}
          <div style={{ 
            marginTop: '1rem', 
            padding: '1rem', 
            background: 'var(--border-light)', 
            borderRadius: 'var(--radius-md)',
            fontSize: '0.875rem',
            color: 'var(--text-secondary)'
          }}>
            <strong>📬 Next Steps:</strong>
            <ol style={{ marginTop: '0.5rem', paddingLeft: '1.25rem' }}>
              <li>Download the RTI as PDF</li>
              <li>Fill in your name, address, phone, and email in the applicant section</li>
              <li>Sign the application</li>
              <li>Attach Rs. 10 postal order or court fee stamp</li>
              <li>Submit physically or via post to the municipal office</li>
            </ol>
          </div>
        </div>
      )}

      {/* Stats Card */}
      <div className="card">
        <h2 className="card-title">📊 Your RTI Stats</h2>
        <div className="grid grid-3">
          <div className="metric">
            <div className="metric-value">{rtiDrafts.length}</div>
            <div className="metric-label">Total Drafts</div>
          </div>
          <div className="metric">
            <div className="metric-value" style={{ color: 'var(--success)' }}>
              {rtiDrafts.filter(d => d.status === 'ready').length}
            </div>
            <div className="metric-label">Ready</div>
          </div>
          <div className="metric">
            <div className="metric-value" style={{ color: 'var(--warning)' }}>
              {rtiDrafts.filter(d => d.status === 'downloaded').length}
            </div>
            <div className="metric-label">Downloaded</div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default RTIPage;
