import React, { useState } from 'react';
import { Detection, AggregatedReport } from '../types';
import { generateRTIDraft } from './rtiGenerator';

// AI-generated RTI drafts based on ride detections
export interface AutoGeneratedRTI {
  id: string;
  generatedAt: number;
  detection: Detection;
  location: {
    latitude: number;
    longitude: number;
    address: string;
    city: string;
    municipalAuthority: string;
  };
  defectType: 'pothole' | 'speed_breaker';
  severity: number;
  content: string;
  status: 'ready' | 'downloaded';
}

// Reverse geocode to get address from coordinates (simplified mock)
async function reverseGeocode(lat: number, lng: number): Promise<{ address: string; city: string }> {
  // In production, use Google Maps, Nominatim, or similar API
  // For demo, return mock addresses based on coordinates
  const mockAddresses: Record<string, { address: string; city: string }> = {
    '28.61-77.20': { address: 'Connaught Place, Near Rajiv Chowk Metro', city: 'New Delhi' },
    '28.63-77.22': { address: 'India Gate Circle, Rajpath', city: 'New Delhi' },
    '28.62-77.21': { address: 'Janpath Road, Near State Emporium', city: 'New Delhi' },
    '28.64-77.21': { address: 'Kashmere Gate, Near ISBT', city: 'New Delhi' },
    '19.07-72.87': { address: 'Marine Drive, Near Churchgate', city: 'Mumbai' },
    '12.97-77.59': { address: 'MG Road, Near Trinity Metro', city: 'Bangalore' },
  };

  const key = `${lat.toFixed(2)}-${lng.toFixed(2)}`;
  return mockAddresses[key] || { 
    address: `Road near ${lat.toFixed(4)}°N, ${lng.toFixed(4)}°E`, 
    city: 'Unknown City' 
  };
}

// Get municipal authority based on city
function getMunicipalAuthority(city: string): string {
  const authorities: Record<string, string> = {
    'New Delhi': 'Municipal Corporation of Delhi (MCD)',
    'Mumbai': 'Brihanmumbai Municipal Corporation (BMC)',
    'Bangalore': 'Bruhat Bengaluru Mahanagara Palike (BBMP)',
    'Chennai': 'Greater Chennai Corporation (GCC)',
    'Kolkata': 'Kolkata Municipal Corporation (KMC)',
    'Hyderabad': 'Greater Hyderabad Municipal Corporation (GHMC)',
  };
  return authorities[city] || 'Municipal Corporation';
}

// AI generates RTI content based on detection data
function generateAIRTIContent(
  detection: Detection,
  address: string,
  city: string,
  authority: string
): string {
  const today = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'long',
    year: 'numeric'
  });
  
  const mapLink = `https://www.google.com/maps?q=${detection.location.latitude},${detection.location.longitude}`;
  const defectName = detection.defectType === 'pothole' ? 'Pothole' : 'Speed Breaker';
  const severityDesc = detection.severity >= 7 ? 'Critical' : detection.severity >= 4 ? 'Moderate' : 'Minor';

  return `
═══════════════════════════════════════════════════════════════════════════════
                    RIGHT TO INFORMATION APPLICATION
                   (Under Section 6(1) of RTI Act, 2005)
═══════════════════════════════════════════════════════════════════════════════

Date: ${today}
Reference No: RW-${Date.now().toString(36).toUpperCase()}

To,
The Public Information Officer
${authority}
${city}

Subject: Information Sought Regarding Road Defect - ${defectName} at ${address}

Sir/Madam,

I, the undersigned, a citizen of India, hereby submit this application under the
Right to Information Act, 2005, seeking information about the following road defect:

═══════════════════════════════════════════════════════════════════════════════
                           DEFECT DETAILS
═══════════════════════════════════════════════════════════════════════════════

Type of Defect    : ${defectName}
Severity Level    : ${detection.severity}/10 (${severityDesc})
Detection Date    : ${new Date(detection.timestamp).toLocaleDateString('en-IN')}
Detection Time    : ${new Date(detection.timestamp).toLocaleTimeString('en-IN')}

Location Details:
• Address         : ${address}
• GPS Coordinates : ${detection.location.latitude.toFixed(6)}°N, ${detection.location.longitude.toFixed(6)}°E
• Map Link        : ${mapLink}

Detection Method  : AI-powered sensor analysis via RoadWatch civic platform
Confidence Score  : ${(detection.confidence * 100).toFixed(0)}%

═══════════════════════════════════════════════════════════════════════════════
                        INFORMATION REQUESTED
═══════════════════════════════════════════════════════════════════════════════

1. Is the above road defect recorded in your maintenance register?

2. Which department/contractor is responsible for this road segment?

3. When was the last inspection conducted at this location?

4. What is the scheduled repair date for this defect?

5. What is the allocated budget for road repairs in this area for FY 2025-26?

6. Have any accidents been reported at this location in the past 12 months?

7. What action has been taken on previous complaints regarding this road?

═══════════════════════════════════════════════════════════════════════════════
                         PUBLIC SAFETY CONCERN
═══════════════════════════════════════════════════════════════════════════════

This ${defectName.toLowerCase()} poses significant risk to:
• Two-wheeler riders and cyclists
• Four-wheeler vehicles
• Pedestrians and senior citizens

Immediate attention is requested to prevent potential accidents and injuries.

═══════════════════════════════════════════════════════════════════════════════
                             DECLARATION
═══════════════════════════════════════════════════════════════════════════════

I declare that:
1. I am a citizen of India.
2. The information sought does not infringe on any person's privacy.
3. I am prepared to pay the prescribed fee of Rs. 10/-.

═══════════════════════════════════════════════════════════════════════════════
                          APPLICANT DETAILS
═══════════════════════════════════════════════════════════════════════════════

Name    : _________________________________

Address : _________________________________

         _________________________________

Phone   : _________________________________

Email   : _________________________________


Signature: _______________________

Date: ${today}

═══════════════════════════════════════════════════════════════════════════════
This RTI was auto-generated by RoadWatch - A citizen-powered road safety initiative
using AI-based defect detection. Report ID: ${detection.id}
═══════════════════════════════════════════════════════════════════════════════
`.trim();
}

// Generate RTI drafts from detections automatically
export async function generateRTIDraftsFromDetections(
  detections: Detection[]
): Promise<AutoGeneratedRTI[]> {
  const drafts: AutoGeneratedRTI[] = [];

  for (const detection of detections) {
    if (detection.defectType === 'normal') continue;
    if (detection.confidence < 0.7) continue;

    const { address, city } = await reverseGeocode(
      detection.location.latitude,
      detection.location.longitude
    );
    const authority = getMunicipalAuthority(city);

    const content = generateAIRTIContent(detection, address, city, authority);

    drafts.push({
      id: `rti-${detection.id}`,
      generatedAt: Date.now(),
      detection,
      location: {
        latitude: detection.location.latitude,
        longitude: detection.location.longitude,
        address,
        city,
        municipalAuthority: authority
      },
      defectType: detection.defectType,
      severity: detection.severity,
      content,
      status: 'ready'
    });
  }

  return drafts;
}

// Demo pre-generated RTI drafts
export const DEMO_AUTO_GENERATED_RTIS: AutoGeneratedRTI[] = [
  {
    id: 'auto-rti-1',
    generatedAt: Date.now() - 3600000,
    detection: {
      id: 'det-1',
      sessionId: 'session-1',
      userId: 'user-1',
      timestamp: Date.now() - 3600000,
      location: { latitude: 28.6139, longitude: 77.2090 },
      defectType: 'pothole',
      confidence: 0.92,
      severity: 8,
      processedWindow: { startTime: 0, endTime: 0, magnitude: 6.2, peakMagnitude: 9.1, averageSpeed: 18, centroid: { latitude: 28.6139, longitude: 77.2090 }, sampleCount: 90 }
    },
    location: {
      latitude: 28.6139,
      longitude: 77.2090,
      address: 'Connaught Place, Near Rajiv Chowk Metro',
      city: 'New Delhi',
      municipalAuthority: 'Municipal Corporation of Delhi (MCD)'
    },
    defectType: 'pothole',
    severity: 8,
    content: '',
    status: 'ready'
  },
  {
    id: 'auto-rti-2',
    generatedAt: Date.now() - 7200000,
    detection: {
      id: 'det-2',
      sessionId: 'session-1',
      userId: 'user-1',
      timestamp: Date.now() - 7200000,
      location: { latitude: 28.6353, longitude: 77.2250 },
      defectType: 'pothole',
      confidence: 0.95,
      severity: 9,
      processedWindow: { startTime: 0, endTime: 0, magnitude: 7.8, peakMagnitude: 11.2, averageSpeed: 15, centroid: { latitude: 28.6353, longitude: 77.2250 }, sampleCount: 92 }
    },
    location: {
      latitude: 28.6353,
      longitude: 77.2250,
      address: 'India Gate Circle, Rajpath',
      city: 'New Delhi',
      municipalAuthority: 'Municipal Corporation of Delhi (MCD)'
    },
    defectType: 'pothole',
    severity: 9,
    content: '',
    status: 'ready'
  },
  {
    id: 'auto-rti-3',
    generatedAt: Date.now() - 10800000,
    detection: {
      id: 'det-3',
      sessionId: 'session-1',
      userId: 'user-1',
      timestamp: Date.now() - 10800000,
      location: { latitude: 28.6280, longitude: 77.2180 },
      defectType: 'speed_breaker',
      confidence: 0.88,
      severity: 5,
      processedWindow: { startTime: 0, endTime: 0, magnitude: 4.1, peakMagnitude: 6.5, averageSpeed: 22, centroid: { latitude: 28.6280, longitude: 77.2180 }, sampleCount: 85 }
    },
    location: {
      latitude: 28.6280,
      longitude: 77.2180,
      address: 'Janpath Road, Near State Emporium',
      city: 'New Delhi',
      municipalAuthority: 'Municipal Corporation of Delhi (MCD)'
    },
    defectType: 'speed_breaker',
    severity: 5,
    content: '',
    status: 'downloaded'
  }
];

// Initialize content for demo RTIs
DEMO_AUTO_GENERATED_RTIS.forEach(rti => {
  rti.content = generateAIRTIContent(
    rti.detection,
    rti.location.address,
    rti.location.city,
    rti.location.municipalAuthority
  );
});
