import jsPDF from 'jspdf';
import { AggregatedReport } from '../types';

export function exportRTIToPDF(
  content: string, 
  report: AggregatedReport,
  filename: string = 'RTI_Application.pdf'
): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;
  
  // Title
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('RIGHT TO INFORMATION APPLICATION', pageWidth / 2, margin, { align: 'center' });
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('(Under Section 6(1) of RTI Act, 2005)', pageWidth / 2, margin + 6, { align: 'center' });

  // Content
  doc.setFontSize(11);
  const lines = doc.splitTextToSize(content, maxWidth);
  
  let y = margin + 15;
  const lineHeight = 5;

  for (const line of lines) {
    if (y > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }

    // Handle section headers (lines with ═══)
    if (line.includes('═══')) {
      doc.setDrawColor(100, 100, 100);
      doc.line(margin, y, pageWidth - margin, y);
      y += 3;
      continue;
    }

    // Bold headers
    if (line.match(/^\d+\.\s+[A-Z]/) || line.startsWith('ROAD DEFECT') || 
        line.startsWith('INFORMATION') || line.startsWith('PUBLIC SAFETY') ||
        line.startsWith('DECLARATION') || line.startsWith('APPLICANT')) {
      doc.setFont('helvetica', 'bold');
    } else {
      doc.setFont('helvetica', 'normal');
    }

    doc.text(line, margin, y);
    y += lineHeight;
  }

  // Footer with map QR placeholder note
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(
    `Generated by RoadWatch | Coordinates: ${report.location.latitude.toFixed(6)}, ${report.location.longitude.toFixed(6)}`,
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  doc.save(filename);
}

export function exportRTIToText(content: string, filename: string = 'RTI_Application.txt'): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
